follower_and_avoider:
  ros__parameters:

    ball_proportional_gain: 1.0
    ball_integral_gain: 1.0
    ball_derivative_gain: 1.0
    
    person_proportional_gain: 1.0
    person_integral_gain: 1.0
    person_derivative_gain: 1.0
    thresh_before_turning: 10000