follower_and_avoider:
  ros__parameters:
    max_linear: 1.5
    max_angular: 3.0
    person_reference_area: 18000.0
    ball_reference_area: 20000.0
    linear_ball_proportional_gain: 0.000015
    linear_ball_integral_gain: 0.0000000001
    linear_ball_derivative_gain: 0.0001

    linear_person_proportional_gain: 0.000015
    linear_person_integral_gain: 0.000001
    linear_person_derivative_gain: 0.000015

    angular_ball_proportional_gain: 0.01
    angular_ball_integral_gain: 0.0001
    # 0.012 ganancia derivativa funciona decente
    angular_ball_derivative_gain: 0.02

    angular_person_proportional_gain: 0.01
    angular_person_integral_gain: 0.0001
    angular_person_derivative_gain: 0.012
